name: kics-github-action

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@94469746ec2c43de89a42fb9d2a80070f5d25b16 # v2.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "./Dockerfile"
          ignore_on_exit: results
          enable_comments: true
          output_path: ./results
          output_formats: json,html
          type: dockerfile
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: results
          path: ./results
